// <auto-generated />
using Exam.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Exam.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameLibrary.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ac")
                        .HasColumnType("integer");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("integer");

                    b.Property<int>("AttackPerRound")
                        .HasColumnType("integer");

                    b.Property<string>("Damage")
                        .HasColumnType("text");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("integer");

                    b.Property<int>("HitPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ac = 12,
                            AttackModifier = 3,
                            AttackPerRound = 1,
                            Damage = "1d6",
                            DamageModifier = 3,
                            HitPoints = 20,
                            Name = "Бабуин"
                        },
                        new
                        {
                            Id = 2,
                            Ac = 13,
                            AttackModifier = -2,
                            AttackPerRound = 3,
                            Damage = "1d6",
                            DamageModifier = 4,
                            HitPoints = 4,
                            Name = "Ашара"
                        },
                        new
                        {
                            Id = 3,
                            Ac = 5,
                            AttackModifier = -3,
                            AttackPerRound = 2,
                            Damage = "1d6",
                            DamageModifier = 3,
                            HitPoints = 12,
                            Name = "Арригал"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
